### ISSUE TITLE
no result

### ISSUE THREAD

**Issue by Au2021** [uct-cbio/proteomics-pipelines#19]
Excuse me, I would like to ask a question. After the program has finished running, I cannot find the results. There is no file similar to "metanovo.fasta" present.

**Comment by Thys3Potgieter** [comment]
Hi there, if for any reason the software fails, it can be restarted and is expected to pick up where it left off. If there are any unprocessed fasta files in the db folder, this can be seen if they are not compressed (ie. not ending in fasta.tar.gz).  If you still have problems, please try to run the pipeline on a single MGF file and the first 1000 entries from the FASTA database, and send me the output folder in archive format?

**Comment by Thys3Potgieter** [comment]
Im closing this issue for now, please open again if you still experience problems.
