### ISSUE TITLE
Error: Could not find or load main clss eu.isas.searchgui.cmd.IdentificationParametersCLI

### ISSUE THREAD

**Issue by cbcolon-pnnl** [uct-cbio/proteomics-pipelines#2]
I'm trying to install and run your software on a VirtualMachine that is running Ubuntu 18.04.  I do steps 1, 3, 4, and 6 from your README.  The following errors happen when I was using your metanovo_v1.6.img with Singularity. From ~/my_metanovo_project  I enter:

singularity shell ~/proteomics-pipelines/singularity/metanovo/metanovo-v1.6.img
metanovo.sh mgf_files/ uniprot_sprot.fasta /home/christian/my_metanovo_project/output/ config.sh

The first time I run this it produces the expected output about editing X!Tandem.  When I rerun it , I get an error about the sg directory not existing in the output//metanovo directory.  I exit singularity and create the folder in the correct location.  When I rerun the code, I get similar errors about a utilities directory and dg directory not existing.  After I create these two folder, I get another error that says Error: Could not find or load main class eu.isas.searchgui.cmd.IdentificationParametersCLI.

**Comment by Thys3Potgieter** [comment]
Dear cbcolon-pnnl, I have updated the metanovo.sh script to load the file paths from the config file, and no longer as command line parameters. These paths should be added as full paths in config.sh. Please let me know if the updated MetaNovo README on master branch still gives this issue.
