### ISSUE TITLE
Runtime and parallelisation

### ISSUE THREAD

**Issue by andrewjmc** [uct-cbio/proteomics-pipelines#3]
Hello,

I couldn't find measures of runtime (absolute or comparative) in the arxiv preprint. Can you give an estimate for the samples in the study?

Also, is it possible to run metanovo by parallelising across nodes on HPC, whether by MPI or simple parallelisation?

Thanks,

Andrew

**Comment by Thys3Potgieter** [comment]
Dear Andrew, I have just done this analysis. On a  32 core Intel Core Processor (Broadwell, IBRS) server with 236Gi and 32 threads set in the MetaNovo config for the analysis of 2 raw files against the December 2019 UniProt release (ca 180 million sequences) a total runtime of 0:09:50:7.2816 was recorded.

**Comment by Thys3Potgieter** [comment]
The PBS implementation (without singularity) does work with multi-node parallelization using gnu-parallel but requires custom installation/configuration for the cluster. Should your nextflow port be available on GitHub please let me know so I can merge / integrate this?
