### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by andrewjmc** [uct-cbio/proteomics-pipelines#5]
There is no file requirements.txt in the lib directory.

**Comment by Thys3Potgieter** [comment]
Hi Andrew, I have added it now.

Best
Thys

**Comment by shrivishalinirajaram** [comment]
The file seems to be missing in the lib directory.

**Comment by Thys3Potgieter** [comment]
Hi there, I will create an updated one soonest - I had removed it due to out of date dependencies. In the meantime, have you tried the singularity based approach for MetaNovo ?

**Comment by shrivishalinirajaram** [comment]
Hi,
I am actually trying to inculcate metanovo to a pipeline. And I do not want to overlay singularity containers on it. 
So, I am trying to perform the manual one.
I will look forward to the file. Thanks!

**Comment by Thys3Potgieter** [comment]
Hi, I have added a requirements.txt for the latest release of MetaNovo (v1.9.4) in the lib folder.

**Comment by shrivishalinirajaram** [comment]
Awesome, Thank you!
